// Copyright 2021 CloudWeGo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package templates

// TestFile .
var TestFile = `// Code generated by thriftgo ({{Version}}). DO NOT EDIT.
package {{GetPackageName .AST}}

import (
	"bytes"
	"testing"
	"reflect"

	gofakeit "github.com/simon0-o/gofakeit/v6"
	"github.com/cloudwego/frugal"
	"github.com/cloudwego/thriftgo/pkg/test"
	"github.com/r3labs/diff/v2"
)

var (
	_ = bytes.Equal
	_ = reflect.DeepEqual
	_ = gofakeit.Struct
	_ = frugal.EncodeObject
	_ = test.Assert
	_ = diff.Diff
)

func Test{{GetPackageTestName .AST}}(t *testing.T) {
	var want, got []byte
	_, _ = want, got
{{- range .Structs}}
{{template "StructLikeTest" .}}
{{- end}}

{{- range .Unions}}
{{template "StructLikeTest" .}}
{{- end}}

{{- range .Exceptions}}
{{template "StructLikeTest" .}}
{{- end}}
}
`

var StructLikeTest = `
{{define "StructLikeTest"}}
{
	s := &{{.GoName}}{}
	gofakeit.Struct(s)
	// test.Assert(t, length == frugal.EncodedSize(s))
	want = make([]byte, s.BLength())
	got = make([]byte, frugal.EncodedSize(s))
	s.FastWriteNocopy(want, nil)
	_, err := frugal.EncodeObject(got, nil, s)
	if err != nil {
		t.Fatal(err)
	}
	wantS := New{{.GoName}}()
	gotS := New{{.GoName}}()
	_, fastErr := wantS.FastRead(want)
	_, err = frugal.DecodeObject(got, gotS)
	if err == nil {
		if !reflect.DeepEqual(wantS, gotS) {
			dlog, _ := diff.Diff(wantS, gotS)
			test.Assert(t, len(dlog) == 0)
		}
	} else if fastErr == nil  {
		t.Fatal(err)
	}
}
{{- end}}{{/* define "StructLikeTest" */}}
`
