// Copyright 2021 CloudWeGo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package templates

// TestFile .
var TestFile = `// Code generated by thriftgo ({{Version}}). DO NOT EDIT.
package {{GetPackageName .AST}}

import (
	"bytes"
	"testing"

	"github.com/brianvoe/gofakeit"
	"github.com/cloudwego/frugal"
	"github.com/cloudwego/thriftgo/pkg/test"
)

var (
	_ = bytes.Equal
	_ = gofakeit.Struct
	_ = frugal.EncodeObject
	_ = test.Assert
)

func Test{{GetPackageTestName .AST}}(t *testing.T) {
	var want, got []byte
	var length int
	_, _, _ = want, got, length
{{- range .Structs}}
{{template "StructLikeTest" .}}
{{- end}}

{{- range .Unions}}
{{template "StructLikeTest" .}}
{{- end}}

{{- range .Exceptions}}
{{template "StructLikeTest" .}}
{{- end}}
}
`

var StructLikeTest = `
{{define "StructLikeTest"}}
{
	s := &{{.GoName}}{}
	gofakeit.Struct(s)
	length = s.BLength()
	// test.Assert(t, length == frugal.EncodedSize(s))
	want = make([]byte, length)
	got = make([]byte, length)
	s.FastWriteNocopy(want, nil)
	frugal.EncodeObject(got, nil, s)
	test.Assert(t, bytes.Equal(want, got))
}
{{- end}}{{/* define "StructLikeTest" */}}
`
